### ISSUE TITLE
Most, but not all, of the XSDs auto-generated for Reg-XML Meta Dictionaries do not define a prefix for the targetNamespace

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#29]

**Comment by palemieux** [comment]
Can you provide a specific example where this is a problem?

For instance, while the XSD generated for Groups (http://www.smpte-ra.org/reg/395/2014/13/1) does not define a prefix for the targetNamespace, this is not an issue since no element defined therein needs to reference another element in the same namespace. The same is true for the elements XSD with namespace http://www.smpte-ra.org/reg/335/2012/13/1.
